### ISSUE TITLE
creating decrease sort

### ISSUE THREAD

**Issue by Abhithecoder-22** [py3-coder/Hacktober_Repo_22#216]
I want t o add some files here

**Comment by Abhithecoder-22** [comment]
mention time complexity

**Comment by py3-coder** [comment]
Not able to understand your Problem @Abhithecoder-22 .Could you Please elaborate little bit more.

**Comment by py3-coder** [comment]
No response Received .
Closing the issue.

**Comment by Abhithecoder-22** [comment]
Sorry  for that, this is my first contribution and I don't understand .
