### ISSUE TITLE
Anyone else facing the same issue ?

### ISSUE THREAD

**Issue by sayskar500** [py3-coder/Hacktober_Repo_22#248]
![image](https://user-images.githubusercontent.com/55600400/194091663-f7e9c104-7c4b-4d90-adf3-a9e7bc9d2f9a.png)

**Comment by py3-coder** [comment]
Wait @sayskar500 let me check..
It happens due having same name.

**Comment by sayskar500** [comment]
Issue resolved @py3-coder !
