### ISSUE TITLE
Contact Management System Using C

### ISSUE THREAD

**Issue by Divya5003** [py3-coder/Hacktober_Repo_22#250]
I want to make a Contact Management System using C. Please add this issue under hacktoberfest.

**Comment by py3-coder** [comment]
Hey @Divya5003  no need to create issue for this u fork this and make this and generate PR..

**Comment by Divya5003** [comment]
Wiil it be considered for the hactoberfest?

**Comment by py3-coder** [comment]
Sure why not but make sure no one has implemented the same in our repo.
Just verify it same project exits in repo or not if not the proceed.
