### ISSUE TITLE
Anyone else facing the same issue ?

### ISSUE THREAD

**Issue by sayskar500** [py3-coder/Hacktober_Repo_22#337]
![image](https://user-images.githubusercontent.com/55600400/194541179-2b6c90d9-8a1a-47ff-a402-9b3441ea6d32.png)

**Comment by py3-coder** [comment]
Hey @sayskar500  wait will fix out.

**Comment by kishumds** [comment]
Yes, I was facing this issue while cloning this repo. @py3-coder can you pls fix this out, so that I make another PR.
Thank you.

**Comment by sayskar500** [comment]
Sure @py3-coder will wait for your response

**Comment by py3-coder** [comment]
Updated @sayskar500 , @kishumds 
Now check and update me..

**Comment by kishumds** [comment]
Yeah, Done 👍

**Comment by sayskar500** [comment]
Yeah ... cool ... done
