### ISSUE TITLE
Has this repo been Excluded from Hacktoberfest 2022 ?

### ISSUE THREAD

**Issue by sayskar500** [py3-coder/Hacktober_Repo_22#359]
![image](https://user-images.githubusercontent.com/55600400/194689903-bdd3dbbb-987b-4436-bdac-8faff240ddae.png)

**Comment by runtime-error2905** [comment]
Yes , Now I checked It has been excluded.
Don't Know the reason behind it.
Almost all DSA Repo is excluded this year..

**Comment by sayskar500** [comment]
I see ... thanks for the confirmation @runtime-error2905
