### ISSUE TITLE
this repo excluded from hacktoberfest

### ISSUE THREAD

**Issue by codeburn12** [py3-coder/Hacktober_Repo_22#369]
<img width="917" alt="ex" src="https://user-images.githubusercontent.com/101239757/194701359-f870e151-3e17-4d11-acac-49f0bd8beda3.png">

**Comment by py3-coder** [comment]
Yes @codeburn12

**Comment by py3-coder** [comment]
We have updated the READEME.md FILE Read there @codeburn12 .
