### ISSUE TITLE
Gold Price Prediction in ML

### ISSUE THREAD

**Issue by aditi072** [py3-coder/Hacktober_Repo_22#409]
Wanted to contribute gold price prediction project in ML, included with frontend. Please allow me to contribute by assigning the issue.
Thankyou!

**Comment by py3-coder** [comment]
Hey @aditi072 contribute to this repo : https://github.com/py3-coder/Model-EDA-Analysis-CART
 if want to contribute in Data Science.
Follow the guidelines and can contribute will reviews it asap.

**Comment by aditi072** [comment]
Okay
